### ISSUE TITLE
混淆的规则怎么填写？

### ISSUE THREAD

**Issue by asdkajdaksd** [24kpk/BaseUIFrame#1]
我在README.md  里没有看到混淆的规则， 请问可以添加下混淆规则吗？

**Comment by 24kpk** [comment]
腾讯官方都未提供混淆规则……

在 2019-10-19 13:17:36，"asdkajdaksd" <notifications@github.com> 写道：


我在README.md 里没有看到混淆的规则， 请问可以添加下混淆规则吗？

**Comment by 24kpk** [comment]
当然，也可以自行手动添加QMUI包下组件混淆规则
